sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 121.37.27.172
    port: 3306
    database: sky_take_out
    username: dongxuanmang
    password: zzx123456789
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    bucket-name: dongxuanmang
    access-key-id: LTAI5t7mYav1FjzhyfPgneCj
    access-key-secret: uXdXg4iqIDI3l4HIS9Y7jlQD9IhQQr
